spring.application.name=customer-service

# Conexión a DB
spring.datasource.url=jdbc:mysql://localhost:3306/dwb_customer_20271
spring.datasource.username=root
spring.datasource.password=Hola$123.,
spring.datasource.driverClassName=com.mysql.jdbc.Driver

